# Generated by Django 6.1.1 on 2026-09-20 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "cars", "verbose_name_plural": "cars"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "drivers", "verbose_name_plural": "drivers"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "verbose_name": "manufacturers",
                "verbose_name_plural": "manufacturers",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="drivers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="taxi.manufacturer",
            ),
        ),
    ]
